export default {
	build: {
		article: {
			1: 'Finished with your map? It\'s time to start building it',
			2: 'Via this function, your entire map will be generated, optimized and archived in a single file',
			3: 'This step may take a few minutes and may cause the application window to freeze. However, don\'t worry and be patient',
		},
		1: 'create temp directory',
		2: 'copy to temp directory',
		3: 'create datapack directory in temp directory',
		4: 'construction of the resource pack',
		5: 'construction of the data pack',
		6: 'clean temp directory of resource and data pack',
		7: 'clean temp directory',
		8: 'your map is ready !',
		download: 'download'
	},
	directory: {
		title: 'Folder path',
		game: 'Game',
		resource: 'Resource',
		save: 'Save',
		temp: 'Tempory'
	},
	minecraftVersion: {
		title: 'You have just changed version',
		version: '{from} to {to}',
		text: 'Changing version is not trivial. Many things can change between different versions of Minecraft, and therefore on the data generated by Mapcraft. Mapcraft will try as far as possible to adapt the data, but errors may occur. Remember to check your data.',
		ok: 'I understand'
	},
	minecraftUser: {
		title: 'Minecraft username',
		tooltip: 'The username you use in the game, this allows Mapcraft to intercept only the commands relating to you'
	},
	name: {
		pack: 'Datapack',
		resource: 'Resourcepack'
	}
};
