stages:
  - build
  - release

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - echo "Building stage"
    - echo "${CI_JOB_ID}" > CI_JOB_ID.txt
    - cp ./src/manifest MANIFEST.json
    - yarn
    - yarn dist
  artifacts:
    paths:
      - CI_JOB_ID.txt
      - MANIFEST.json
      - ./out/*.zip
      - ./out/*.deb
      - ./out/*.rpm
      - ./out/*.exe
      - ./out/*.blockmap
    expire_in: 3 days
  rules:
    - if: $CI_COMMIT_TAG

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "v$CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --ref $CI_COMMIT_SHA \
      --assets-link "{\"name\":\"Windows setup\",\"url\":\"https://gitlab.com/some/repo/-/jobs/`cat CI_JOB_ID.txt`/artifacts/out/mapcraft_win.exe\"}" \
      --assets-link "{\"name\":\"Windows setup blockmap\",\"url\":\"https://gitlab.com/some/repo/-/jobs/`cat CI_JOB_ID.txt`/artifacts/out/mapcraft_win.exe.blockmap\"}" \
      --assets-link "{\"name\":\"Windows archive\",\"url\":\"https://gitlab.com/some/repo/-/jobs/`cat CI_JOB_ID.txt`/artifacts/out/mapcraft_win.zip\"}" \
      --assets-link "{\"name\":\"DEB-based package\",\"url\":\"https://gitlab.com/some/repo/-/jobs/`cat CI_JOB_ID.txt`/artifacts/out/mapcraft_linux.deb\"}" \
      --assets-link "{\"name\":\"RPM-based package\",\"url\":\"https://gitlab.com/some/repo/-/jobs/`cat CI_JOB_ID.txt`/artifacts/out/mapcraft_linux.rpm\"}" \
      --assets-link "{\"name\":\"Linux archive\",\"url\":\"https://gitlab.com/some/repo/-/jobs/`cat CI_JOB_ID.txt`/artifacts/out/mapcraft_linux.tar.gz\"}" \
      --assets-link "{\"name\":\"MacOS archive\",\"url\":\"https://gitlab.com/some/repo/-/jobs/`cat CI_JOB_ID.txt`/artifacts/out/mapcraft_mac.tar.gz\"}"
  rules:
    - if: $CI_COMMIT_TAG
