stages:
  - build
#  - release

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - echo "Building stage"
    - echo "${CI_JOB_ID}" > ./out/CI_JOB_ID.txt
    - yarn
    - yarn dist
  artifacts:
    paths:
      - ./out/
    expire_in: 30 days

#release:
#  stage: release
#  image
    
#deploy-job:
#  stage: deploy 
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
