name: Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: apt-update
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get update && sudo apt-get upgrade -y
      - name: yarn
        run: yarn && yarn build
      - name: build-mac
        if: startsWith(matrix.os, 'macos-latest')
        run: yarn production:mac
      - name: build-linux
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: yarn production:linux
      - name: build-windows
        if: startsWith(matrix.os, 'windows-latest')
        run: yarn production:windows
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./dist/electron-build

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./dist/electron-build
      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/electron-build/Mapcraft_linux.AppImage
            ./dist/electron-build/Mapcraft_linux.7z
            ./dist/electron-build/Mapcraft_mac.dmg
            ./dist/electron-build/Mapcraft_mac.dmg.blockmap
            ./dist/electron-build/Mapcraft_mac.7z
            ./dist/electron-build/Mapcraft_win.exe
            ./dist/electron-build/Mapcraft_win.exe.blockmap
            ./dist/electron-build/Mapcraft_win.7zip
